version: "3.8"
services:
  app:
    stdin_open: true
    build:
      context: .
    ports: 
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
    env_file:
      - .env
    networks:
      - main
networks:
  main: null
